import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Pagefind search index — generated by the postbuild script, not our code.
    "public/pagefind/**",
    // Local isolated branches contain their own generated output and sources.
    ".worktrees/**",
  ]),
]);

export default eslintConfig;
